### ISSUE TITLE
Backport request: 1.19.3

### ISSUE THREAD

**Issue by Mr-Jokes-3** [MDLC01/better-selection-mc#3]
are there any plans to backport to 1.19.3?

**Comment by MDLC01** [comment]
I normally only support the latest version of Minecraft.

However, if you don't mind using an older version of Better Selection, you can install [Better Selection 1](https://github.com/MDLC01/better-selection-mc/releases/tag/v1), which I just marked as compatible with Minecraft 1.19.3. Keep in mind that this version did not support macOS shortcuts properly, though.
