### ISSUE TITLE
Mouse selection gets misaligned on specific condition

### ISSUE THREAD

**Issue by ParanYeonpil** [MDLC01/better-selection-mc#5]
When the visible part of the text is moved, the mouse selection is misaligned
Regardless of the currently visible part, the selectable range is based on the first letter

https://github.com/MDLC01/better-selection-mc/assets/165812336/28807e33-db8a-4a3f-a49f-6e6092c0be45

**Comment by MDLC01** [comment]
The fix is available in the latest version (1.6).
